### ISSUE TITLE
请问一下，为什么mac os 下使用，显示done，但是没有修改成功

### ISSUE THREAD

**Issue by a49942245a** [Xhofe/ipa-renamer#1]
系统mac os 10.13.6 
<img width="1139" alt="企业微信截图_4109df34-7ab7-4a3b-9b7d-59fe55e5899b" src="https://user-images.githubusercontent.com/47873762/192206755-8a3c2d9e-9b3d-47ff-9508-541f49b89e70.png">

显示是已经完成了，但是源文件并没有重命名，已经给文件777权限了。求解答

**Comment by xhofe** [comment]
默认输出目录为`你运行的目录/renamed`下。

**Comment by a49942245a** [comment]
他是一个隐藏文件夹吗？为什么我并没有/renamed这个文件夹，ipa目录里也没有。

有点小白，还劳烦大佬能耐心教一下，感谢感谢
![Uploading Xnip2022-09-26_14-32-04.jpg…]()

**Comment by a49942245a** [comment]
![Xnip2022-09-26_14-32-04](https://user-images.githubusercontent.com/47873762/192208412-ed00efbf-a8ca-42eb-9457-9ee74766616c.jpg)
他是一个隐藏文件夹吗？为什么我并没有/renamed这个文件夹，ipa目录里也没有。

有点小白，还劳烦大佬能耐心教一下，感谢感谢

**Comment by xhofe** [comment]
你是在 `/Users/xdf` 运行的，输出目录就是 `/Users/xdf/renamed`

**Comment by a49942245a** [comment]
搞定了，谢谢大佬

**Comment by a49942245a** [comment]
![Xnip2022-09-26_19-49-45](https://user-images.githubusercontent.com/47873762/192269107-e086ec14-d542-4a68-87e6-70ac425000c4.jpg)
大佬，又遇到问题了，是哪里语法有问题吗，只输入单独的一个包，就能修改成功，*的话就好像把一个包转向了另一个包，这是啥情况，求解，拜托了

**Comment by a49942245a** [comment]
还是说，他就是只能一个包一个包的弄呢

**Comment by xhofe** [comment]
不相关问题 请重新打开一个issue，不要复用已关闭的issue。
