### ISSUE TITLE
不知道是不是语法错误，报这个错误

### ISSUE THREAD

**Issue by a49942245a** [Xhofe/ipa-renamer#2]
抱歉哈老哥，第一次用提问。
![Xnip2022-09-26_19-49-45](https://user-images.githubusercontent.com/47873762/192287662-053fe9d0-a041-493b-80fc-ff943d384ef0.jpg)
一个一个拖入的话，是没有问题的，但是用*的命令的时候，就会出现下图错误，是语法问题还是他本身就不支持批量修改呢。望答复

**Comment by xhofe** [comment]
类Unix 使用通配符时需要使用`''`将pattern包裹起来。比如：
```bash
$ ./ipa_renamer './ipa/*'
```

**Comment by a49942245a** [comment]
明白了，搞定了，感谢大佬耐心讲解，感谢感谢
