### ISSUE TITLE
macos 13.3.1 (22E261)  用不了

### ISSUE THREAD

**Issue by ssrlist** [Xhofe/ipa-renamer#4]
ipa_renamer-x86_64-apple-darwin.tar用的这个包,,在macos12上可以的,,今天升级13后,不行了

**Comment by ssrlist** [comment]
提示
segmentation fault

**Comment by xhofe** [comment]
你可以尝试clone源码自行编译

**Comment by ssrlist** [comment]
编译教程看的一头雾水,毫无头绪

**Comment by ssrlist** [comment]
实在是弄不来编译啊,能更新下吗?

**Comment by xhofe** [comment]
https://github.com/Xhofe/ipa-renamer/blob/main/README.md#run-from-source

**Comment by Crueyl** [comment]
搞定了,以前从来没build过,,没这个概念,感谢
